# Generated by Django 5.2.5 on 2025-10-19 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registrations',
            field=models.ManyToManyField(blank=True, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
