# Generated by Django 5.2.5 on 2025-10-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('concert', 'Concert'), ('meetup', 'Meetup'), ('webinar', 'Webinar')], default='conference', max_length=20),
            preserve_default=False,
        ),
    ]
